llm:
  api_type: open_llm
  base_url: 'http://0.0.0.0:30000/v1'
  model: 'llama3-8b'


embedding:
  api_type: "openai"  # or azure / ollama / groq etc.
  base_url: "https://cfcus02.opapi.win/v1"  # or forward url / other llm url
  api_key: "sk-XVBaWFFC3af98090Dc32T3BLbkFJ0Ba9481790144B1eaA6B"
  model: "text-embedding-3-small"
  dimensions: 128
  max_token_size: 8102
  embed_batch_size: 128
  embedding_func_max_async: int = 16
