llm:
  api_type: "openai"
  base_url: "https://api.openai.com/v1"
  model: "gpt-3.5-turbo"
  api_key: "YOUR_OPENAI_API_KEY_HERE"

embedding:
  api_type: "openai"
  api_key: "YOUR_OPENAI_API_KEY_HERE"
  model: "text-embedding-3-small"
  cache_dir: ""
  dimensions: 1024
  max_token_size: 8102
  embed_batch_size: 128
  embedding_func_max_async: 16

data_root: "./Data"

working_dir: ./results
exp_name: test

# Optional: Disable ColBERT to avoid dependency issues
# Set to true if you encounter ColBERT/transformers compatibility problems
disable_colbert: false
